channels:
  - conda-forge
dependencies:
  - blosc
  - chxtools  # no package on PyPI
  - fabio
  - gpytorch
  - jupyterhub-singleuser=1.3.0  # match JupyterHub deployment version
  - jupyterlab=3.2.*
  - nodejs
  - numba
  - openmpi>=4.1.4
  - pip  # mamba warns us to explicitly list this dependency
  - py-xgboost
  - pyarrow
  - pycentroids
  - pyfai
  - pystackreg
  - python-blosc
  - python-graphviz
  - python=3.9
  - pytorch
  - sasview
  - shadow3
  - srwpy
  - xraylarch>=0.9.45
  - zarr
  - pip:
    - amostra
    - area-detector-handlers
    - arvpyf
    - atsas-pipelines
    - bokeh
    - boto3
    - bottleneck
    - csxtools>=0.1.14
    - dask
    - dask-image
    - dask-jobqueue
    - dask-labextension
    - dask-ml
    - dask-xgboost
    - databroker>=2.0.0b10
    - edrixs>=0.0.8
    - eiger-io
    - graphviz
    - h5py>=3.6
    - hvplot
    - hxntools
    - ipympl
    - line_profiler
    - lixtools
    - lmfit>=0.9.9
    - matplotlib>=3.5
    - memory_profiler
    - mendeleev
    - mimesis
    - modestimage
    - nbclassic>=0.2.8
    - nbconvert-webpdf
    - nbgitpuller
    - nbserverproxy
    - notebook
    - nslsii
    - numexpr
    - numpy>=1.22
    - openmpi>=4.1.4
    - pandas
    - papermill
    - periodictable
    - photutils
    - py4xs
    - pychx>=4.1.2
    - pyhyperscattering[all]
    - pymongo
    - pypdf2
    - pytables
    - pyxrf>=0.0.9
    - pyzbar
    - reportlab
    - requests
    - scikit-learn
    - scipy>=1.9
    - seaborn
    - sip
    - sixtools>=0.0.2
    - smi-analysis>=0.2.0
    - tiled>=0.1.0a74
    - tornado
    - tzlocal<3  # tzlocal 3 broke API on Python 3.7 and the fix turned into a rabbithole
    - voila
    - xarray
    - xray-vision>=0.0.10
